import {useState, useEffect, Fragment} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import moviesData from '../public/movies.json'
import Checkbox from './comp/Checkbox'

export default function Home() {
  const [rangeval, setRangeval] = useState(1);
  const [movieGenre, setMovieGenre] = useState({});
  const [keys, setKeys] = useState([]);
  var countKey1 = 0;
  var countKey2 = 0;

  useEffect(() => {
    console.log("test")

    var genresOccurrences = {};
    moviesData.forEach((movieData) => {
      movieData['genres'].forEach((movieGenres) => {
        if (genresOccurrences[movieGenres]) {
          genresOccurrences[movieGenres] += 1;
        } else {
          genresOccurrences[movieGenres] = 1;
        };
      })
    })

    setMovieGenre(genresOccurrences)
    setKeys(Object.keys(genresOccurrences))
  }, [])

  function handleChange(event) {
    console.log("test")
    setRangeval(event.target.value);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>
          Welcome to the <a href="https://nextjs.org">Seach Index</a> POC
        </h1>
        <div className={styles.blockTop}>
          <div>
            <b>Search:</b> <input type="search" name="" id="" />
          </div>
          <div>
            <select name="cars" id="cars">
              <option value="asc">Rating ASC</option>
              <option value="desc">Rating DESC</option>
            </select>
          </div>
        </div>

        <div className={styles.blockLeft}>
            <div>
                Min Rating = {rangeval} <input type="range" min="1" max="10" className="slider" id="myRange" value={rangeval} onChange={handleChange} />
            </div>
            <div>
              <b>Genres:</b>
              { Object.entries(movieGenre).map((t,k) =>  
                <div>
                  <input type="checkbox" name={t[0]} value={t[0]} />
                  <label htmlFor={t[0]}>{t[0]}: {t[1]}</label> <br />
                </div>
              )}    
            </div>
        </div>

        <div className={styles.blockRight}>
          {moviesData.map(movieData => 
                    <div className={styles.card}>
                      <h4>Title: {movieData['title']}</h4>
                      <a><b>Year:</b> {movieData['year']}</a> <br />
                    </div> 
                  )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
