import {useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import data from '../public/imdb.json';

export default function Home() {
  const [rangeval, setRangeval] = useState(1);


  function handleChange(event) {
    setRangeval(event.target.value);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>
          Welcome to the <a href="https://nextjs.org">Seach Index</a> POC
        </h1>

        <div className={styles.card}>
          <div>
          <b>Search:</b> <input type="search" name="" id="" />
          </div>
          <div>
            <select name="cars" id="cars">
              <option value="asc">Rating ASC</option>
              <option value="desc">Rating DESC</option>
            </select>
          </div>
          <div>
            Min Rating = {rangeval} <input type="range" min="1" max="10" class="slider" id="myRange" value={rangeval} onChange={handleChange} />
          </div>
        </div>

        {data.map(d => 
          <div className={styles.card}>
            <h4>Title: {d['name']}</h4>
            <a><b>Description:</b> {d['description']}</a> <br />
            <a><b>Tags:</b> {d['tags']}</a>
          </div> 
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
